module.exports = (sequelize, DataTypes) => sequelize.define('returnOrder', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: false, // Automatically gets converted to SERIAL for postgres
  },
  number: DataTypes.STRING,
  customerid: DataTypes.STRING,
  customername: DataTypes.STRING,
  customercode: DataTypes.STRING,
  customeridnumber: DataTypes.STRING,
  customeremail: DataTypes.STRING,
  customerphone: DataTypes.STRING,
  customeraddress: DataTypes.STRING,
  customerpostcode: DataTypes.STRING,
  customerprovince: DataTypes.STRING,
  customerdistrict: DataTypes.STRING,
  customersubdistrict: DataTypes.STRING,
  customerstreetAddress: DataTypes.STRING,
  customerbranchname: DataTypes.STRING,
  customerbranchno: DataTypes.STRING,
  reference: DataTypes.STRING,
  warehousecode: DataTypes.STRING,
  status: DataTypes.STRING,
  paymentstatus: DataTypes.STRING,
  amount: DataTypes.INTEGER,
  vatamount: DataTypes.FLOAT,
  shippingvat: DataTypes.INTEGER,
  shippingamount: DataTypes.INTEGER,
  returnorderdate: DataTypes.STRING,
  returnorderdateString: DataTypes.STRING,
  paymentamount: DataTypes.INTEGER,
  description: DataTypes.TEXT,
  discount: DataTypes.STRING,
  vattype: DataTypes.INTEGER,
  saleschannel: DataTypes.STRING,
  vatpercent: DataTypes.INTEGER,
  createdby: DataTypes.STRING,
  createusername: DataTypes.STRING,
  createuserid: DataTypes.INTEGER,
  createdatetime: DataTypes.STRING,
  createdatetimeString: DataTypes.STRING,
  updatedatetime: DataTypes.STRING,
  updatedatetimeString: DataTypes.STRING,
  referenceid: DataTypes.INTEGER,
  referencenumber: DataTypes.STRING,
  uniquenumber: DataTypes.STRING,
});
